- title: A Reinforcement Learning Look at Risk-Sensitive Linear Quadratic Gaussian
    Control
  authors:
    - Leilei Cui
    - "Tamer Ba\u015Far"
    - Zhong-Ping Jiang
  publisher: Proceedings of The 5th Annual Learning for Dynamics and Control Conference
  date: 2023-06
  link: https://proceedings.mlr.press/v211/cui23c.html

- title: Learning-Based Control: Tools and Applications to Robotics
  publisher: ProQuest
  authors:
    - Leilei Cui    
  date: 2024-05
  link: https://www.proquest.com/openview/f63b8aefe3197f9c49b1333aa6cb0f18/1?pq-origsite=gscholar&cbl=18750&diss=y

