- title: A Reinforcement Learning Look at Risk-Sensitive Linear Quadratic Gaussian
    Control
  publisher: Proceedings of The 5th Annual Learning for Dynamics and Control Conference
  date: '2023-06'
  link: https://proceedings.mlr.press/v211/cui23c.html
  orcid: 0000-0001-8031-7638
  leilei-cui: true
  updated: 2023-11-02
  plugin: orcid.py
  file: orcid-leilei.yaml

- title: 'Learning-Based Control: Tools and Applications to Robotics'
  publisher: 'ProQuest'
  date: '2024-05'
  link: https://www.proquest.com/openview/f63b8aefe3197f9c49b1333aa6cb0f18/1?pq-origsite=gscholar&cbl=18750&diss=y
  orcid: 0000-0001-8031-7638
  leilei-cui: true
  updated: 2025-11-02
  plugin: orcid.py
  file: orcid-leilei.yaml